Add explicit algorithm steps for TypedArrays.
tc39/proposal-array-find-from-last pull request #45
Opened 2021-04-15 19:23 UTC by DanielRosenwasser

Fixes #41.
Fixes #43.
Subsumes #44 .

2021-04-15 19:24 UTC, bakkot commented on spec.html
> +    1. Let _len_ be ? LengthOfArrayLike(_O_) - 1.
```suggestion
    1. Let _len_ be ? LengthOfArrayLike(_O_).
```

?

2021-04-15 19:25 UTC, DanielRosenwasser commented on spec.html
> +    1. Let _len_ be ? LengthOfArrayLike(_O_) - 1.
D'oh.

2021-04-15 19:27 UTC, bakkot commented on spec.html
> +      1. Let _kValue_ be ? Get(_O_, _Pk_).
```suggestion
      1. Let _kValue_ be ! Get(_O_, _Pk_).
```

2021-04-15 19:32 UTC, DanielRosenwasser commented on spec.html
> +      1. Let _kValue_ be ? Get(_O_, _Pk_).
This one should also be `!`, right?

```suggestion
      1. Let _kValue_ be ! Get(_O_, _Pk_).
```

2021-04-15 19:36 UTC, bakkot commented on spec.html
> +      1. Let _kValue_ be ? Get(_O_, _Pk_).
Yup.

2021-04-15 19:40 UTC, leobalter requested changes
Small nitpicks, otherwise, LGTM

2021-04-15 19:40 UTC, leobalter commented on spec.html
> +    1. Repeat, while _k_ &ge; 0
```suggestion
    1. Repeat, while _k_ &ge; 0,

```

2021-04-15 19:40 UTC, leobalter commented on spec.html
> +    1. Repeat, while _k_ &ge; 0
```suggestion
    1. Repeat, while _k_ &ge; 0,

```

2021-04-15 19:41 UTC, leobalter commented
The same applies to the original methods in the Array.prototype. It seems like adding a `,` to the end of a while was recently added to ECMA-262.

2021-04-15 19:47 UTC, bakkot commented
> It seems like adding a `,` to the end of a while was recently added to ECMA-262.

In https://github.com/tc39/ecma262/pull/1985, yes.

The linter in ecmarkup will enforce this sort of thing, but it's not yet entirely suited for use proposals. I generally don't worry about stuff like this until the PR to ecma262, when CI will catch it.

2021-04-15 19:54 UTC, leobalter commented
Sure thing, I just meant to add this comment as the review is mostly on nitpicking. It's alright to ignore my review as it doesn't change goals for the normative aspects of the proposal.

2021-04-15 20:28 UTC, DanielRosenwasser commented
Commas should be fixed up now.

2021-04-15 20:28 UTC, leobalter approved these changes

2021-04-15 21:33 UTC, ljharb approved these changes

2021-04-16 03:07 UTC, Kingwl approved these changes
Thanks to all!

2021-04-16 03:08 UTC, merged